accounts/urls.py
from django.urls import path
from .views import *

app_name = "accounts"
urlpatterns = [
    path('login/', login, name="login"),
    path('logout/', logout, name="logout"),
    path('signup/', signup, name="signup"),
]

main/urls.py
from django.urls import path
from .views import *
from . import views

app_name = "main"
urlpatterns = [
    path('', views.mainpage, name="mainpage"),
    path('new-post/', views.new_post, name="new-post"),
    path('free/', views.freepage, name="freepage"),
    path('create', views.create, name="create"),
    path('<int:id>', views.detail, name="detail"),
    path('edit/<int:id>', views.edit, name="edit"),
    path('update/<int:id>', views.update, name="update"),
    path('delete/<int:id>', views.delete, name="delete"),
    path('comment/<int:comment_id>/delete/', views.delete_comment, name="delete_comment"),
    path('tag-list', views.tag_list, name="tag-list"),
    path('tag-posts/<int:tag_id>', views.tag_posts, name="tag-posts"),
    path('likes/<int:post_id>',likes, name="likes"),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('accounts.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import *
from . import views

app_name="users"

urlpatterns = [
    path('mypage/<int:user_id>', views.mypage, name='mypage'),
    path('follow/<int:id>', follow, name="follow"),
]

project/templates/shared/_navbar.html
<nav class="navbar-container">
    <!-- mainpage 링크 연결-->
    <a class="navbar-link" href="{% url 'main:mainpage' %}">13th_Silver's note</a>
    <!-- secondpage 링크 연결-->
    <a class="navbar-link" href="{% url 'main:freepage' %}">Free Page</a>
    <a class="navbar-link" href="{% url 'main:tag-list' %}">Tag</a>

    <div class="nav-right">
        {% if user.is_authenticated %}
        <!--로그인 시 보이는 화면-->
        <ul class="nav-link-account">
            <li class="nav-link-user">{{user.username}}</li>
            <li><a href="{% url 'accounts:logout' %}">로그아웃</a></li>
            <li><a href="{% url 'users:mypage' user_id=user.id %}">mypage</a></li>
        </ul>
        {% else %}
        <!--로그아웃 시 보이는 화면-->
        <ul class="nav=link-account">
            <li><a href="{% url 'accounts:login' %}">로그인</a></li>
            <li><a href="{% url 'accounts:signup' %}">signup</a></li>
        </ul>
        {% endif %}
    </div>
</nav>