main/urls.py
from django.urls import path
from .views import *
from . import views

app_name = "main"
urlpatterns = [
    path('', views.mainpage, name="mainpage"),
    path('new-post/', views.new_post, name="new-post"),
    path('free/', views.freepage, name="freepage"),
    path('create', views.create, name="create"),
    path('<int:id>', views.detail, name="detail"),
    path('edit/<int:id>', views.edit, name="edit"),
    path('update/<int:id>', views.update, name="update"),
    path('delete/<int:id>', views.delete, name="delete"),
    path('comment/<int:comment_id>/delete/', views.delete_comment, name="delete_comment"),
    path('tag-list', views.tag_list, name="tag-list"),
    path('tag-posts/<int:tag_id>', views.tag_posts, name="tag-posts"),
    path('likes/<int:post_id>',likes, name="likes"),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('accounts.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import *
from . import views

app_name="users"

urlpatterns = [
    path('mypage/<int:user_id>', views.mypage, name='mypage'),
    path('follow/<int:id>', follow, name="follow"),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User 
from main.models import Post #main앱의 Post모델을 import

# Create your models here.
class UserPost(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE) #유저와 연결
    post = models.ForeignKey(Post, on_delete=models.CASCADE) #Post 모델과 연결

    def __str__(self):
        return f"User {self.user.username} Post {self.post.title}"
    
    def summary(self):
        return self.post.summary()

users/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import auth
from django.contrib.auth.models import User
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from .models import Post
from main.models import Post

# Create your views here.

@login_required
def mypage(request, user_id):
    # 로그인한 유저의 글만 가져오기
    user = get_object_or_404(User, pk=user_id)
    posts = Post.objects.filter(writer=user)
    context = {
        'user':user,
        'posts':posts, #유저가 작성한 글 목록
    }
    return render(request, 'users/mypage.html', context)

def follow(request, id):
    user = request.user
    followed_user = get_object_or_404(User, pk=id)
    is_follower=user.profile in followed_user.profile.followers.all()
    if is_follower:
        user.profile.followings.remove(followed_user.profile)
    else:
        user.profile.followings.add(followed_user.profile)
    return redirect('users:mypage', followed_user.id)

users/templates/users/edit.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h2>수정중..!</h2>
<form action="{% url 'users:update' post.id %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <p>N주차 : <input type="text" name="title" value="{{post.title}}"></p>
    
    <p>난이도 :
    <select name="difficulty">
        <option value="easy">쉬움</option>
        <option value="normal" selected>보통</option>
        <option value="hard">어려움</option>
    </select>
    </p>
    
    <p>내용 : <textarea type="text" name="content" id="" cols="30" rows="10">{{post.content}}</textarea></p>
    <button type="submit">제출</button>
</form>
{% endblock %}

users/templates/users/mypage.html
{% extends 'base.html' %}
{% block content %}

<!-- following & followers-->
User : {{user}} <br>
UserProfile : {{user.profile}} <br>
<p>🤩 팔로워 :{{ user.profile.followers.count}}명 | 팔로잉 :{{ user.profile.followings.count}}명 🤩</p>
{% if request.user != user %}
    {% if request.user.profile in user.profile.followers.all %}
        <a href="{% url 'users:follow' user.id %}">
            <button type="button" class="btn btn-outline-info">언팔로우</button>
        </a>
    {% else %}
        <a href="{% url 'users:follow' user.id %}">
            <button type="button" class="btn btn-info">팔로우</button>
        </a>
    {% endif %}
{% endif %}

<!-- 글 작성하기 -->
<h2 class="contents">🩵글 작성🩵</h2>
<div>
    <div>
        {% if user.is_authenticated %}
        <a href="{% url 'main:new-post' %}">새로운 글 작성하기!</a> 
        {% endif %}
    </div>
</div>
    
<!-- 작성된 글 목록-->
<h2 class="contents">💙내가 작성한 글💙</h2>
<div class="contents"></div>
<div>
    {% for post in posts %}
    </div>
        <hr/>
        <h3><a href="{% url 'main:detail' post.id %}">{{post.title}}</a></h3>
        난이도 : {% if post.difficulty == 'easy' %}쉬움
        {% elif post.difficulty == 'normal' %}보통
        {% elif post.difficulty == 'hard' %}어려움
        {% endif %} | {{post.pub_date}}<br>
        {{post.summary}}
        <br>
    </div>
    {% empty %}
    <p>아직 글이 없네요! 첫 글을 작성해볼까요?</p>
    {% endfor %}
</div>

{% endblock %}

users/templates/users/new-post.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<form action="{% url 'users:create' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <p>N주차 : <input type="text" name="title"></p>

    <p style="display: flex; align-items: center;">
    난이도 : 
    <select name="difficulty" style="margin-left: 10px; margin-top: 10px; width: auto;">
        <option value="easy">쉬움</option>
        <option value="normal" selected>보통</option>
        <option value="hard">어려움</option>
    </select>
    </p>

    <p>내용 : <textarea type="text" name="content" id="" cols="30" rows="10"></textarea></p>
    <button type="submit">제출</button>
</form>

{% endblock %}