main/urls.py
from django.urls import path
from .views import *
from . import views

app_name = "main"
urlpatterns = [
    path('', views.mainpage, name="mainpage"),
    path('new-post/', views.new_post, name="new-post"),
    path('free/', views.freepage, name="freepage"),
    path('create', views.create, name="create"),
    path('<int:id>', views.detail, name="detail"),
    path('edit/<int:id>', views.edit, name="edit"),
    path('update/<int:id>', views.update, name="update"),
    path('delete/<int:id>', views.delete, name="delete"),
    path('comment/<int:comment_id>/delete/', views.delete_comment, name="delete_comment"),
    path('tag-list', views.tag_list, name="tag-list"),
    path('tag-posts/<int:tag_id>', views.tag_posts, name="tag-posts"),
    path('likes/<int:post_id>',likes, name="likes"),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('accounts.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import *
from . import views

app_name="users"

urlpatterns = [
    path('mypage/<int:user_id>', views.mypage, name='mypage'),
    path('follow/<int:id>', follow, name="follow"),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

# Post 모델을 main앱에만 정의하고, writer 필드로 User와 관계를 설정
class Tag(models.Model):
    name = models.CharField(max_length=30, null=False, blank=False)

    def __str__(self):
        return self.name

class Post(models.Model):
    title = models.CharField(max_length=50)
    writer = models.ForeignKey(User, null=False, blank=False, on_delete=models.CASCADE)
    difficulty = models.CharField(max_length=30)
    content = models.TextField()
    pub_date = models.DateField()
    image = models.ImageField(upload_to="post/", blank=True, null=True)
    tags = models.ManyToManyField(Tag, related_name='posts', blank=True)
    like = models.ManyToManyField(User, related_name='likes', blank=True)
    like_count = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title
    
    def summary(self):
        return self.content[:20]
    
class Comment(models.Model): 
    content = models.TextField()
    pub_date = models.DateTimeField()
    writer = models.ForeignKey(User, null=False, blank=False, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, null=False, blank=False, on_delete=models.CASCADE)

    def str(self):
        return self.blog.title + " : " + self.content[:20] + "by" + self.writer.profile.nickname

main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone

from .models import *
from .models import Post


# Create your views here.

def mainpage(request):
    return render(request, 'main/mainpage.html')

def freepage(request):
    posts = Post.objects.all()
    print(posts) #글이 제대로 로드되었는지 확인
    return render(request, 'main/freepage.html',{'posts': posts})

def new_post(request):
    return render(request, 'main/new-post.html')

def detail(request, id):
    post = get_object_or_404(Post, pk=id)
    if request.method == 'GET':
        comments = Comment.objects.filter(post=post)
        return render(request, 'main/detail.html', {'post':post, 'comments': comments})
    
    elif request.method == 'POST':
        new_comment=Comment()
        new_comment.post = post
        new_comment.writer = request.user
        new_comment.content = request.POST['content']
        new_comment.pub_date = timezone.now() 
        new_comment.save()
        return redirect('main:detail', id)

def create(request):
    if request.user.is_authenticated:
        new_post = Post()

        new_post.title = request.POST['title']
        new_post.writer = request.user #로그인한 유저를 작성자로 설정
        new_post.difficulty = request.POST['difficulty']
        new_post.content = request.POST['content']
        new_post.pub_date = timezone.now()
        new_post.image = request.FILES.get('image')
        new_post.save()
        
        import re #tag에서 띄어쓰기, 줄바꿈 등의 모든 공백을 대상으로 만들 때 사용
        words = re.split(r'\s+',new_post.content.strip()) #공백을 기준으로 분리. 원래는 split(' ')을 이용하여 or의 방식으로 ' '와 '\n'을 나타낼 수 있는지 보았지만 불가능한듯 ㅠ
        tag_list = []
        #나눈 단어가 '#'으로 시작한다면 tag_list에 저장
        for w in words:
            if w.startswith('#') and len(w)>1:
                tag_list.append(w[1:]) #tag_list에 있는 Tag들을 new_post의 tags에 추가
                    
        for t in tag_list:
            tag, boolean = Tag.objects.get_or_create(name=t)
            new_post.tags.add(tag.id)

        return redirect('main:detail', new_post.id)
    else:
        return redirect('accounts:login')

def edit(request, id):
    edit_post = Post.objects.get(pk=id)
    return render(request, 'main/edit.html', {"post": edit_post})

def update(request, id):
    update_post = Post.objects.get(pk=id)
    if request.user.is_authenticated and request.user == update_post.writer:
        update_post.title = request.POST['title']
        update_post.difficulty = request.POST['difficulty']
        update_post.content = request.POST['content']
        update_post.pub_date = timezone.now()

        if request.FILES.get('image'):
            update_post.image = request.FILES.get('image')
        update_post.save()

        import re
        #해시태그 추출하기
        words = re.split(r'\s+',update_post.content.strip())

        #중간에,, 먼저..! 기존 태그 삭제
        update_post.tags.clear()

        tag_list=[]
        for w in words:
            if w.startswith('#') and len(w)>1:
                tag_list.append(w[1:])
                    
        for t in tag_list:
            tag, boolean=Tag.objects.get_or_create(name=t)
            update_post.tags.add(tag.id)

        return redirect('main:detail', update_post.id)
    return redirect('accounts:login', update_post.id)

def delete(request, id):
    delete_post = Post.objects.get(pk=id)
    delete_post.delete()
    return redirect('main:freepage')

def delete_comment(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    comment.delete()
    return redirect('main:detail', comment.post.id)

def tag_list(request): #모든 태그 목록을 볼 수 있는 페이지
    tags = Tag.objects.all()
    return render(request, 'main/tag-list.html', {'tags': tags})

def tag_posts(request, tag_id): #특정 태그를 가진 게시글의 목록을 볼 수 있는 페이지
    tag = get_object_or_404(Tag, id=tag_id)
    posts = tag.posts.all()
    return render(request, 'main/tag-post.html', {
        'tag' : tag,
        'posts' : posts
    })

def likes(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.user in post.like.all():
        post.like.remove(request.user)
        post.like_count -= 1
        post.save()
    else:
        post.like.add(request.user)
        post.like_count += 1
        post.save()
    return redirect('main:detail', post.id)

main/templates/main/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


    <h3>{{post.title}}</h3>
    <a href="{% url 'users:mypage' user_id=post.writer.id %}">작성자 : {{post.writer}}</a>
        | 난이도 : {% if post.difficulty == 'easy' %}쉬움
                {% elif post.difficulty == 'normal' %}보통
                {% elif post.difficulty == 'hard' %}어려움
                {% endif %}
        | 세션 날짜 : {{post.pub_date}}

        <a href="{% url 'main:likes' post.id %}">
            {% if user in post.like.all %} ❤️ {% else %} 🤍 {% endif %}
        </a>
        {{post.like_count}}개

        <p>
            {% for tag in post.tags.all %}
                <a href="{% url 'main:tag-posts' tag.id %}">#{{ tag.name }}</a>
            {% endfor %}
        </p>
        <hr/>
        <p>{{post.content}}</p>

        <!-- 로그인한 유저가 작성한 글만 수정/삭제 가능 -->
        {% if post.writer == user %}  
            <a href="{% url 'main:edit' post.id %}">글 수정하기</a>
            <a href="{% url 'main:delete' post.id %}">글 삭제하기</a>
        {% endif %}
    <br>


    <div class="comment_container">

        <div class="comment_form">
            <h2></h2>
            <form action="{% url 'main:detail' post.id %}" method="POST">
                {% csrf_token %} <!-- Djago에서 보안을 위해 반드시 포함해야 하는 요소-->
                댓글 쓰기 : <input type="text" name="content">
                <input type="submit" name="submit">
            </form>
        </div>

        <div class="comment_list">
            {% for comment in comments %}
            <hr>
            <h4>작성자 : {{comment.writer}}</h4>
            <p>내용 : {{comment.content}}</p>
            <p>{{comment.pub_date}}</p>

            <!-- 삭제 버튼 (유저 본인 댓글일 때만 뜬다)-->
            {% if request.user.is_authenticated and comment.writer == request.user %}
            <form action="{% url 'main:delete_comment' comment.id %}" method="POST">
                {% csrf_token %}
                <button type="submit">삭제</button>
            </form>
            {% endif %}

            {% endfor %}
        </div>

    </div>


{% endblock %}

main/templates/main/edit.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h2>수정중..!</h2>
<form action="{% url 'main:update' post.id %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <p>N주차 : <input type="text" name="title" value="{{post.title}}"></p>
    
    <p>난이도 :
    <select name="difficulty">
        <option value="easy">쉬움</option>
        <option value="normal" selected>보통</option>
        <option value="hard">어려움</option>
    </select>
    </p>
    
    <p>내용 : <textarea type="text" name="content" id="" cols="30" rows="10">{{post.content}}</textarea></p>
    <button type="submit">제출</button>
</form>
{% endblock %}

main/templates/main/freepage.html
{% extends 'base.html' %}
{% block content %}

<!-- 글 작성하기 -->
<h2 class="contents">🌷새 글 작성🌷</h2>
<div>
    <div>
        {% if user.is_authenticated %}
        <a href="{% url 'main:new-post' %}">새로운 글 작성하기!</a> 
        {% else %}
        <p>로그인하고 새 글을 작성해보세요!</p>
        {% endif %}
    </div>
</div>

<h2 class="contents">🌸 세션 기록들 🌸</h2>
<div class="contents"></div>
<div>
    {% for post in posts %}
        <hr/>
        <div>
            <h3><a href="{% url 'main:detail' post.id %}">{{post.title}}</a></h3>
            작성자: {{post.writer.username}} | 난이도 : {% if post.difficulty == 'easy' %}쉬움
            {% elif post.difficulty == 'normal' %}보통
            {% elif post.difficulty == 'hard' %}어려움
            {% endif %} | {{post.pub_date}}<br>
            {{post.summary}}
            <br>
        </div>
    {% empty %}
        <p>작성된 글이 없습니다. 가장 먼저 글을 작성해보세요!</p>
    {% endfor %}
</div>

{% endblock %}

main/templates/main/mainpage.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<img src="{%static 'images/blossom.jpg' %}" alt="flower" width="100px">
<h2 class="contents">🌸 안녕하세용! 은지의 노트입니당😎 🌸</h2>
<div class="contents"></div>
<h2>🦁 로그인 후, MyPage를 이용해보세요! 🦁</h2>


{% endblock %}

main/templates/main/new-post.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<form action="{% url 'main:create' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <p>N주차 : <input type="text" name="title"></p>

    <p style="display: flex; align-items: center;">
    난이도 : 
    <select name="difficulty" style="margin-left: 10px; margin-top: 10px; width: auto;">
        <option value="easy">쉬움</option>
        <option value="normal" selected>보통</option>
        <option value="hard">어려움</option>
    </select>
    </p>

    <p>내용 : <textarea type="text" name="content" id="" cols="30" rows="10"></textarea></p>
    <button type="submit">제출</button>
</form>

{% endblock %}

main/templates/main/tag-list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div>
    <h1>🧩 해시태그 목록 🔗</h1>
    <hr>
    {% for t in tags %}
    <div>
        <h2><a href="{% url 'main:tag-posts' t.id %}">#{{t.name}}</a></h2>
    </div>
    {% endfor %}
</div>
{% endblock %}

main/templates/main/tag-post.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div>
    <h1>#{{tag}}가 달린 게시글</h1>
    <hr>
    <div>
    {% for p in posts %}
        <hr/>
        <h3>{{p.title}}</h3>
        {{p.writer}} | {{p.pub_date}}<br>
        {{p.summary}}
        <a href="{% url 'main:detail' p.id %}">[자세히 보기]</a>
        <br>
        {% endfor %}
    </div>
</div>
{% endblock %}